print("Exit the Zachry building on the Bizzell Street side of the building.")
print()
print("Facing the street, continue right on Bizzell")
print()
print("Once at the intersection between Bizzell and Ross, take a right")
print()
print("Continue straight on Ross until you reach the fish plaza and fountain.")
print("Turn left on Houston once reaching this intersection.")
print()
print("Almost instantly, turn right on Jones Street.")
print()
print("Continue on Jones until you reach the Albritton Bell Tower.")
print()
print("Upon reaching the bell tower, turn right on Old Main.")
print()
print("Continue on Old Main through the underpass until the intersection between Old Main and Olsen Bvd.")
print()
print("Turn left on Olsen Bvd and continue straight until you reach Reed Arena on your right.")